version: '3.7'
services:
  pocketbase:
    build: ./pocketbase
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - /path/to/data:/pb_data
      - /path/to/public:/pb_public
      - /path/to/hooks:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - apinet
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    env_file: .env
    command: server --console-address ":9001" /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 10;  /usr/bin/mc alias set myminio http://minio:9000 checknote 89898989; /usr/bin/mc mb
      myminio/checknote; /usr/bin/mc anonymous set public myminio/checknote;  exit 0;  "
  hocuspocus:
    build: server/
    ports:
      - 1234:1234
    env_file:
      - .env
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    networks:
      - apinet

networks:
  apinet:
    driver: bridge

volumes:
  minio_storage:
